# Generated by Django 4.2.3 on 2023-08-30 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='newuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=120)),
                ('Prénom', models.CharField(max_length=120)),
                ('Date_de_naissance', models.DateField()),
                ('Num_tel', models.PositiveBigIntegerField(unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cin', models.PositiveIntegerField(unique=True)),
            ],
        ),
    ]
