# Generated by Django 4.2.3 on 2023-08-31 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='mot_de_passe',
            field=models.CharField(default='', max_length=256, unique=True),
        ),
        migrations.AddField(
            model_name='newuser',
            name='pseudo',
            field=models.CharField(default=0, max_length=256, unique=True),
            preserve_default=False,
        ),
    ]
