# Generated by Django 4.2.3 on 2023-08-31 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_newuser_mot_de_passe_newuser_pseudo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='mot_de_passe',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='pseudo',
        ),
    ]
