# Generated by Django 4.2.3 on 2023-08-31 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_remove_newuser_mot_de_passe_remove_newuser_pseudo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='cin',
        ),
    ]
