# Generated by Django 4.2.3 on 2023-08-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_user', models.CharField(max_length=120)),
                ('Lastname_user', models.CharField(max_length=120)),
                ('Name_agence', models.CharField(max_length=120)),
                ('Dateofbirth', models.DateField()),
                ('phone_number', models.PositiveBigIntegerField(max_length=15, unique=True)),
                ('email_user', models.EmailField(max_length=254, unique=True)),
                ('user_cin', models.PositiveIntegerField(unique=True)),
                ('nb_bus', models.PositiveIntegerField()),
                ('nb_guides', models.PositiveIntegerField()),
            ],
        ),
    ]
