# Generated by Django 4.2.3 on 2023-08-11 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agence',
            name='phone_number',
            field=models.PositiveBigIntegerField(unique=True),
        ),
    ]
