# Generated by Django 4.2.3 on 2024-05-13 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_x', models.CharField(max_length=50)),
                ('player_o', models.CharField(max_length=50)),
                ('current_player', models.CharField(default='X', max_length=1)),
                ('board_state', models.CharField(default='---------', max_length=9)),
                ('winner', models.CharField(blank=True, max_length=1, null=True)),
            ],
        ),
    ]
